<?php
/* <img src="<?php ?>" style='width:20%;height:30vh' >*/
?>
<div id="owlslider" class="products list items product-items">
   <ul>
     <li>1</li>
     <li>2 </li>
     <li>3</li>
     <li>4</li>
     <li>5</li>       
  </ul>
</div>
    <script>
    (function  () {
        require(["jquery","myowl"],function($,owl) {
            $(document).ready(function() {
                $("#owlslider").owlCarousel({
                    navigation : true, // Show next and prev buttons
                    autoPlay: false, //Set AutoPlay to 3 seconds 
                    items : 5
                });
            });
        });
    });
    </script>
    
